mykytaso_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", include("webapp.urls", namespace="webapp")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from .views import UserDetailView, RegisterView, UserUpdateView, UserPasswordChangeView

app_name = "users"

urlpatterns = [
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/me/", UserDetailView.as_view(), name="user-detail"),
    path("accounts/me/update/", UserUpdateView.as_view(), name="user-update"),
    path("accounts/me/password_change/", UserPasswordChangeView.as_view(), name="password-change"),
    path("accounts/", include("django.contrib.auth.urls")),
]

webapp/urls.py
from django.urls import path

from webapp.views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostChangePositionView,
    TagCreateView,
    TagDeleteView,
    BlockCreateView,
    BlockDeleteView,
    BlockChangePositionView,
    AboutMeView,
    ResumeView,
    MessageCreateView,
    CommentCreateView,
    CommentDeleteView,
)

app_name = "webapp"

urlpatterns = [
    path("", PostListView.as_view(), name="index"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("posts/create/", PostCreateView.as_view(), name="post_create"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path(
        "post/change-position/",
        PostChangePositionView.as_view(),
        name="post_change_position",
    ),
    path(
        "posts/<int:pk>/content/create/",
        BlockCreateView.as_view(),
        name="block_create",
    ),
    path(
        "posts/<int:pk>/content/delete/",
        BlockDeleteView.as_view(),
        name="block_delete",
    ),
    path(
        "posts/<int:pk>/content/change-position/",
        BlockChangePositionView.as_view(),
        name="block_change_position",
    ),
    path("posts/<int:pk>/tag/create/", TagCreateView.as_view(), name="tag_create"),
    path("posts/<int:pk>/tag/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path(
        "posts/<int:pk>/comment/create/",
        CommentCreateView.as_view(),
        name="comment_create",
    ),
    path(
        "posts/<int:pk>/comment/delete/",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path("about", AboutMeView.as_view(), name="about_me"),
    path("resume/", ResumeView.as_view(), name="resume"),
    path("send_message/", MessageCreateView.as_view(), name="send_message"),
]

templates/includes/block_creation_panel.html
<div class="row mt-md-3 mb-md-4 mt-2 mb-3 justify-content-center">
  <div id="content-creator-panel-field" class="col-11 col-md-8 col-lg-8 px-4 px-lg-5 py-3 border">

    <h5 class="fw-bold text-center my-3"><i class="bi bi-pencil-square"></i>&nbsp;&nbsp;Block Creation Panel</h5>

    <!-- Text Form -->
    <form class="row py-3 px-0 align-items-center" method="post" action="{% url 'webapp:block_create' post.id %}">

      {% csrf_token %}
      <div class="col-auto m-0 px-2">
        <select class="form-select rounded-5" aria-label="select_text_alignment" name="text_alignment">
          <option value="text-start">Left</option>
          <option value="text-center">Center</option>
          <option value="text-end">Right</option>
        </select>
      </div>

      <div class="col-auto m-0 px-2">
        <select class="form-select rounded-5" aria-label="select_text_type" name="text_type">
          <option value="normal_text">Normal</option>
          <option value="text_bold">Bold</option>
          <option value="text_italic">Italic</option>
          <option value="text_image_description">Image</option>
          <option value="text_title_h1">H1</option>
          <option value="text_title_h2">H2</option>
          <option value="text_title_h3">H3</option>
          <option value="text_title_h4">H4</option>
          <option value="text_title_h5">H5</option>
        </select>
      </div>

      <div class="col m-0 px-2">
        <div class="input-group">
          <input class="form-control rounded-start-5" aria-label="text" name="text" placeholder="" required>
          <button id="creator_panel_button" type="submit" class="btn btn-outline-primary rounded-end-5" ><i class="bi bi-file-text"></i> Add Text</button>
        </div>
      </div>

    </form>

    <!-- Image Form -->
    <form class="row py-3 px-0 align-items-center" method="post" action="{% url 'webapp:block_create' post.id %}" enctype="multipart/form-data">

      {% csrf_token %}
      <div class="col-auto m-0 px-2">
        <select class="form-select rounded-5" aria-label="select_image_alignment" name="image_alignment">
          <option value="text-center">Center</option>
          <option value="text-start">Left</option>
          <option value="text-end">Right</option>
        </select>
      </div>

      <div class="col-auto m-0 px-2">
        <select class="form-select rounded-5" aria-label="select_image_size" name="image_size">
          <option value="100">100%</option>
          <option value="75">75%</option>
          <option value="50">50%</option>
          <option value="25">25%</option>
        </select>
      </div>

      <div class="col m-0 px-2">
        <div class="input-group">
          <input type="file" class="form-control rounded-start-5" aria-label="upload_image" name="image" required>
          <button id="creator_panel_button" class="btn btn-outline-primary rounded-end-5" type="submit"><i class="bi bi-file-image"></i> Add Image</button>
        </div>
      </div>

    </form>

    <!-- Space Form -->
    <form class="row py-3 px-0 align-items-center justify-content-end" method="post" action="{% url 'webapp:block_create' post.id %}">
      {% csrf_token %}
      <div class="col-auto m-0 px-2">
        <div class="input-group">

          <input type="number"
                 class="form-control rounded-start-5"
                 id="add-space"
                 name="space_number"
                 placeholder="16"
                 value="16"
                 min="1"
                 max="100"
                 step="1"
                 aria-label="space_number"
                 required>
          <span class="input-group-text">px</span>
          <button id="creator_panel_button" class="btn btn-outline-primary rounded-end-5" type="submit"><i class="bi bi-file"></i> Add Space</button>
        </div>
      </div>

    </form>

  </div>
</div>

templates/includes/comment_form.html
<div class="row justify-content-center">
  <div  class="col-11 col-md-8 col-lg-8 px-4 px-lg-5 pt-3 pt-lg-4 mb-5 mt-2 mt-md-3 rounded-5 border">
    <form class="row justify-content-center" method="post" action="{% url 'webapp:comment_create' post.id %}">
      {% csrf_token %}
      <textarea class="col form-control m-0 rounded-4" name="comment_content" aria-label="comment" rows="4" placeholder="Write a comment..." required></textarea>
      <div class="row justify-content-center">
        <button type="submit" class="col-auto btn btn-primary my-3 rounded-5">Comment</button>
      </div>
    </form>
  </div>
</div>

templates/includes/footer.html
{% load static %}

<footer class="mt-auto">
  <div class="container text-center">

    <div class="row py-2 justify-content-center">

      <div class="col-auto">
        <a href="https://github.com/mykytaso/">
          <img src="{% static 'icons/icon_git.png' %}" alt="GitHub" height="34">
        </a>
      </div>

      <div class="col-auto">
        <a href="https://www.linkedin.com/in/mykytaso/">
          <img src="{% static 'icons/icon_in.png' %}" alt="LinkedIn" height="34">
        </a>
      </div>

      <div class="col-auto">
        <a href="https://www.codewars.com/users/mykytaso/">
          <img src="{% static 'icons/icon_cw.png' %}" alt="Codewars" height="34">
        </a>
      </div>

      <div class="col-auto">
        <a href="https://www.instagram.com/mykytaso/">
          <img src="{% static 'icons/icon_inst.png' %}" alt="Instagram" height="34">
        </a>
      </div>

      <div class="col-auto">
        <a class="" href="https://savelife.in.ua/en/donate-en/">
          <img src="{% static 'icons/icon_cba.png' %}" alt="Come Back Alive" height="34">
        </a>
      </div>


    </div>

    <div class="row justify-content-center pt-2 pb-3">
      <div class="col-auto">
        <small class="text-black-50"><i class="bi bi-c-circle"></i> 2025 Mykyta Soloviov</small>
      </div>
    </div>

  </div>
</footer>

templates/includes/navbar.html
{% load static %}


<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">

    <!-- Toggler for smaller screens -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Content -->
    <div class="collapse navbar-collapse" id="navbarNav">

      {% with request.resolver_match.url_name as url_name %}
        <ul class="navbar-nav mx-auto test-sm-center">

          <li class="nav-item">
            <a class="btn btn-outline-primary btn-sm rounded-4 mx-2 mt-3 {% if url_name == "index" %}active{% endif %}" href="{% url 'webapp:index' %}" role="button">Home</a>
          </li>

          <li class="nav-item">
            <a class="btn btn-outline-primary btn-sm rounded-4 mx-2 mt-3 {% if url_name == "about_me" %}active{% endif %}" href="{% url 'webapp:about_me' %}" role="button">About me</a>
          </li>

          <li class="nav-item">
            <a class="btn btn-outline-primary btn-sm rounded-4 mx-2 mt-3 {% if url_name == "resume" %}active{% endif %}" href="{% url 'webapp:resume' %}" role="button">Resume</a>
          </li>

          <li class="nav-item">
            <a class="btn btn-outline-primary btn-sm rounded-4 mx-2 mt-3 {% if url_name == "send_message" %}active{% endif %}" href="{% url 'webapp:send_message' %}" role="button">Send message</a>
          </li>

          <li class="nav-item">
            {% if user.is_authenticated %}

              <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <span class="input-group">
                  <a class="btn btn-outline-primary btn-sm rounded-start-4 ms-2 mt-3 {% if url_name == "user-detail" %}active{% endif %}" href="{% url 'users:user-detail' %}" role="button"><i class="bi bi-person-fill"></i></a>
                  <button type="submit" class="btn btn-outline-primary btn-sm rounded-end-4 me-2 mt-3 ">Logout</button>
                </span>
              </form>

            {% else %}

              <span class="input-group">
                <a class="btn btn-outline-primary btn-sm rounded-start-4 ms-2 mt-3 {% if url_name == "login" %}active{% endif %}" href="{% url 'users:login' %}" role="button">Login</a>
                <a class="btn btn-outline-primary btn-sm rounded-end-4 me-2 mt-3 {% if url_name == "register" %}active{% endif %}" href="{% url 'users:register' %}" role="button">Register</a>
              </span>

            {% endif %}
          </li>

        </ul>
      {% endwith %}

    </div>

  </div>
</nav>