mykytaso_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", include("webapp.urls", namespace="webapp")),
    path("", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from .views import UserDetailView, RegisterView, UserUpdateView, UserPasswordChangeView

app_name = "users"

urlpatterns = [
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/me/", UserDetailView.as_view(), name="user-detail"),
    path("accounts/me/update/", UserUpdateView.as_view(), name="user-update"),
    path("accounts/me/password_change/", UserPasswordChangeView.as_view(), name="password-change"),
    path("accounts/", include("django.contrib.auth.urls")),
]

webapp/urls.py
from django.urls import path

from webapp.views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    PostChangePositionView,
    TagCreateView,
    TagDeleteView,
    BlockCreateView,
    BlockDeleteView,
    BlockChangePositionView,
    AboutMeView,
    ResumeView,
    MessageCreateView,
    CommentCreateView,
    CommentDeleteView,
)

app_name = "webapp"

urlpatterns = [
    path("", PostListView.as_view(), name="index"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("posts/create/", PostCreateView.as_view(), name="post_create"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path(
        "post/change-position/",
        PostChangePositionView.as_view(),
        name="post_change_position",
    ),
    path(
        "posts/<int:pk>/content/create/",
        BlockCreateView.as_view(),
        name="block_create",
    ),
    path(
        "posts/<int:pk>/content/delete/",
        BlockDeleteView.as_view(),
        name="block_delete",
    ),
    path(
        "posts/<int:pk>/content/change-position/",
        BlockChangePositionView.as_view(),
        name="block_change_position",
    ),
    path("posts/<int:pk>/tag/create/", TagCreateView.as_view(), name="tag_create"),
    path("posts/<int:pk>/tag/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path(
        "posts/<int:pk>/comment/create/",
        CommentCreateView.as_view(),
        name="comment_create",
    ),
    path(
        "posts/<int:pk>/comment/delete/",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path("about", AboutMeView.as_view(), name="about_me"),
    path("resume/", ResumeView.as_view(), name="resume"),
    path("send_message/", MessageCreateView.as_view(), name="send_message"),
]

webapp/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

from webapp.models import Message, Post


class MessageForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    class Meta:
        model = Message
        fields = ["email", "content"]
        labels = {
            "email": "Your Email Address",
            "content": "Your Message",
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["cover_image", "cover_title", "cover_description"]

webapp/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.db.models.aggregates import Max
from django.http import HttpResponseForbidden, HttpResponseBadRequest
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic, View

from webapp.forms import MessageForm
from webapp.models import Message, Post, Text, Block, Image, Space, Tag, Comment


class SuperuserRequiredMixin:
    """Mixin to restrict access to superusers only."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return HttpResponseForbidden(
                _("Forbidden: You do not have permission to access this page.")
            )
        return super().dispatch(request, *args, **kwargs)


class LoginRequiredCustomMixin:
    """Mixin to restrict access to logged-in users only."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden(
                _("Forbidden: You do not have permission to access this page.")
            )
        return super().dispatch(request, *args, **kwargs)


class PostListView(generic.ListView):
    model = Post
    template_name = "webapp/index.html"


class PostCreateView(SuperuserRequiredMixin, generic.CreateView):
    model = Post
    fields = ["cover_image", "cover_title", "cover_description"]
    template_name = "webapp/post_create.html"
    success_url = reverse_lazy("webapp:index")


class PostUpdateView(SuperuserRequiredMixin, generic.UpdateView):
    model = Post
    fields = ["cover_image", "cover_title", "cover_description"]
    template_name = "webapp/post_update.html"
    success_url = reverse_lazy("webapp:index")


class PostDeleteView(SuperuserRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy("webapp:index")


class PostChangePositionView(SuperuserRequiredMixin, View):
    def post(self, request):
        post_position = request.POST.get("post_position")
        position_direction = request.POST.get("position_direction")

        if not post_position or not position_direction:
            return HttpResponseBadRequest(
                "Both 'post_position' and 'position_direction' are required."
            )

        post = get_object_or_404(Post, position=post_position)

        if position_direction == "left":
            next_post = (
                Post.objects.filter(position__gt=post.position)
                .order_by("position")
                .first()
            )
            if next_post:
                post.position, next_post.position = (
                    next_post.position,
                    post.position,
                )
                post.save()
                next_post.save()

        if position_direction == "right":
            next_post = (
                Post.objects.filter(position__lt=post.position)
                .order_by("-position")
                .first()
            )
            if next_post:
                post.position, next_post.position = (
                    next_post.position,
                    post.position,
                )
                post.save()
                next_post.save()

        return redirect("webapp:index")


class PostDetailView(generic.DetailView):
    model = Post
    template_name = "webapp/post_detail.html"

    def get_queryset(self):
        return Post.objects.prefetch_related(
            "comments__author", "blocks__content_object", "tags"
        )


class BlockCreateView(SuperuserRequiredMixin, View):
    def post(self, request, pk):
        post = get_object_or_404(Post, id=pk)

        text = request.POST.get("text")
        image = request.FILES.get("image")
        space = request.POST.get("space_number")

        if text:
            new_object = Text.objects.create(
                text=text,
                text_type=request.POST.get("text_type"),
                text_alignment=request.POST.get("text_alignment"),
            )

        elif image:
            new_object = Image.objects.create(
                image=image,
                image_size=request.POST.get("image_size"),
                image_alignment=request.POST.get("image_alignment"),
                post=post,
            )

        elif space:
            new_object = Space.objects.create(space_number=int(space))

        else:
            return redirect("webapp:post_detail", pk=post.id)

        # Create new block associated with the new object
        object_type = ContentType.objects.get_for_model(new_object)
        max_position = Block.objects.filter(post=post).aggregate(Max("block_position"))
        block_position = (
            max_position["block_position__max"] + 1
            if max_position["block_position__max"]
            else 1
        )

        Block.objects.create(
            post=post,
            object_type=object_type,
            object_id=new_object.id,
            block_position=block_position,
        )

        return redirect("webapp:post_detail", pk=post.id)


class BlockDeleteView(SuperuserRequiredMixin, View):
    def post(self, request, pk):
        block_id = request.POST.get("block_id")

        if not block_id:
            return HttpResponseBadRequest("Block ID is required.")

        block = get_object_or_404(Block, id=block_id)

        # Delete the content object first
        block.content_object.delete()

        # Delete the Block association
        block.delete()

        return redirect("webapp:post_detail", pk=pk)


class BlockChangePositionView(SuperuserRequiredMixin, View):
    def post(self, request, pk):
        post = get_object_or_404(Post, id=pk)
        block_id = request.POST.get("block_id")
        block_direction = request.POST.get("block_direction")

        if not block_id or not block_direction or not post:
            return HttpResponseBadRequest(
                "Both 'block_id' and 'block_direction' are required."
            )

        block = get_object_or_404(Block, id=block_id)

        if block_direction == "up":
            next_block = (
                Block.objects.filter(post=post, block_position__lt=block.block_position)
                .order_by("-block_position")
                .first()
            )
            if next_block:
                block.block_position, next_block.block_position = (
                    next_block.block_position,
                    block.block_position,
                )
                block.save()
                next_block.save()

        if block_direction == "down":
            next_block = (
                Block.objects.filter(post=post, block_position__gt=block.block_position)
                .order_by("block_position")
                .first()
            )
            if next_block:
                block.block_position, next_block.block_position = (
                    next_block.block_position,
                    block.block_position,
                )
                block.save()
                next_block.save()

        return redirect("webapp:post_detail", pk=pk)


class TagCreateView(SuperuserRequiredMixin, View):
    def post(self, request, pk):
        post = get_object_or_404(Post, id=pk)
        tag_name = request.POST.get("tag_name")
        Tag.objects.create(tag_name=tag_name, post=post)

        return redirect("webapp:post_detail", pk=pk)


class TagDeleteView(SuperuserRequiredMixin, View):
    def post(self, request, pk):
        tag_id = request.POST.get("tag_id")
        Tag.objects.filter(id=tag_id).delete()

        return redirect("webapp:post_detail", pk=pk)


class CommentCreateView(LoginRequiredCustomMixin, View):
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        current_user = request.user
        comment_content = request.POST.get("comment_content")

        if not comment_content:
            return HttpResponseBadRequest("Comment content is required.")

        Comment.objects.create(post=post, author=current_user, content=comment_content)

        return redirect("webapp:post_detail", pk=pk)


class CommentDeleteView(LoginRequiredCustomMixin, View):
    def post(self, request, pk):
        comment_id = request.POST.get("comment_id")
        comment = get_object_or_404(Comment, id=comment_id)

        if request.user == comment.author or request.user.is_superuser:
            comment.delete()
            return redirect("webapp:post_detail", pk=pk)
        else:
            return HttpResponseForbidden(
                _("You do not have permission to delete this comment.")
            )


class AboutMeView(generic.TemplateView):
    template_name = "webapp/about_me.html"


class ResumeView(generic.RedirectView):
    url = "https://flowcv.com/resume/2ij133mut7p8"


class MessageCreateView(generic.CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("webapp:send_message")

    def form_valid(self, form):
        messages.success(self.request, "success")
        return super().form_valid(form)

templates/webapp/about_me.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="container">

    <div class="row mt-md-5 mt-1 justify-content-center">
      <div class="col-auto fs-2 fw-bolder">
        About me
      </div>
    </div>

    <div class="row mt-md-3 mb-md-4 mt-2 mb-3 justify-content-center">
      <div id="post-field" class="col-11 col-md-8 col-lg-8 p-4 p-lg-5 border">

        <p>Hi, my name is Mykyta, and I’m a Python Developer.</p>
        <p>I love engineering stuff, and programming is the perfect tool for me to do so. In the physical space, I have fun messing around with Fusion 360 and 3D Printing.</p>
        <p>
          <span class="fw-semibold">Locations:</span><br>
          🇺🇸&nbsp; USA, FL <span class="fw-lighter">(2024–Present)</span><br>
          🇵🇹&nbsp; Portugal <span class="fw-lighter">(2017–2024)</span><br>
          🇺🇦&nbsp; Ukraine <span class="fw-lighter">(Until 2017)</span>
        </p>

      </div>
    </div>

  </div>

{% endblock %}

templates/webapp/index.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}


{% block content %}

  <div class="container">

    <div class="row mt-md-5 mb-md-4 mt-1 mb-3 justify-content-center">
      <div class="col-auto fs-2 fw-bolder">
        👋 Hi! I'm Mykyta

        <!-- Create Post Button -->
        {% if user.is_staff %}
          &nbsp;<a class="btn btn-link" href="{% url 'webapp:post_create' %}"><i class="bi bi-plus-square-fill h4"></i></a>
        {% endif %}

      </div>
    </div>

    <div class="row justify-content-center">

    {% for post in object_list %}
      <div class="col-auto mb-4">

        <!-- Post Card -->
        <a href="{% url 'webapp:post_detail' post.id %}" class="text-decoration-none">
          <div class="card" style="width: 18rem; border-radius: 20px;">
            {% if post.cover_image %}
              <img id="card-img-top-corners" src="{{ post.cover_image.url }}" class="card-img-top" alt="">
            {% else %}
              No image.
            {% endif %}

            <div class="card-body">
              <h5 class="card-title text-decoration-none text-dark">{{ post.cover_title }}</h5>
              <p class="card-text text-decoration-none text-dark">{{ post.cover_description }}</p>
            </div>
          </div>
        </a>

        <!-- Editing Buttons -->
        {% if user.is_staff %}
          <div class="row justify-content-center p-0 my-2">
            <div class="col-auto border rounded-5" style="background: white">

              <div class="row py-2 m-0 justify-content-center align-items-center">
                <form class="col-auto p-0 m-0 pe-3" action="{% url 'webapp:post_change_position' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="post_position" value="{{ post.position }}">
                  <input type="hidden" name="position_direction" value="left">
                  <button type="submit" {% if forloop.first %} disabled {% endif %} class="btn btn-link m-0 p-0"><i class="bi bi-caret-left"></i></button>
                </form>

                <div class="col-auto p-0 m-0"><a class="px-3" href="{% url 'webapp:post_update' post.id %}"><i class="bi bi-pen"></i></a></div>

                <div class="col-auto p-0 m-0"><a class="px-3" href="{% url 'webapp:post_delete' post.id %}" ><i class="bi bi-trash"></i></a></div>

                <form class="col-auto p-0 m-0 ps-3" action="{% url 'webapp:post_change_position' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="post_position" value="{{ post.position }}">
                  <input type="hidden" name="position_direction" value="right">
                  <button type="submit" {% if forloop.last %} disabled {% endif %} class="btn btn-link m-0 p-0"><i class="bi bi-caret-right"></i></button>
                </form>
              </div>

            </div>
          </div>
        {% endif %}

      </div>

    {% endfor %}

    </div>

  </div>

{% endblock %}

templates/webapp/message_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  
  <div class="container">

    {% if messages %}

      {% for message in messages %}
        <div class="row mt-md-5 mb-md-4 mt-1 mb-3 justify-content-center">
          <div class="col-auto fs-2 fw-bolder">
            Got it! Thanks for reaching out 🤘
          </div>
        </div>
      {% endfor %}

    {% else %}

      <div class="row mt-md-5 mb-md-4 mt-1 mb-3 justify-content-center">
        <div class="col-auto fs-2 fw-bolder">
          Send Me a Message
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-10 col-md-8 col-lg-6 fw-medium">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form | crispy}}
            <div class="text-center my-3 mt-md-5">
              <button type="submit" class="btn btn-primary rounded-5">
                <i class="bi bi-send"></i> Send
              </button>
            </div>
          </form>
        </div>
      </div>

    {% endif %}

  </div>
  
{% endblock %}

templates/webapp/post_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">

  <div class="row mt-md-5 mb-md-4 mt-1 mb-3 justify-content-center">
    <div class="col-auto fs-2 fw-bolder">
      Delete this post?
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-auto mb-4">
      <div class="card" style="width: 18rem; border-radius: 20px;">
        {% if post.cover_image %}
          <img id="card-img-top-corners" src="{{ object.cover_image.url }}" class="card-img-top" alt="">
        {% else %}
          No image.
        {% endif %}
        <div class="card-body">
          <h5 class="card-title text-decoration-none text-dark">{{ object.cover_title }}</h5>
          <p class="card-text text-decoration-none text-dark">{{ object.cover_description }}</p>
        </div>
      </div>
    </div>
  </div>


  <div class="row mb-4 justify-content-center">
    <div class="col-auto mx-2">
      <a href="{% url 'webapp:index' %}">
          <button class="btn btn-outline-primary btn-sm rounded-4">Cancel</button>
      </a>
    </div>
    <div class="col-auto mx-2">
      <form method="post">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-outline-danger btn-sm rounded-4" type="submit" value="Delete">
      </form>
    </div>
  </div>

</div>

{% endblock %}

templates/webapp/post_create.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="container">

  <div class="row mt-md-5 mb-md-4 mt-1 mb-3 justify-content-center">
    <div class="col-auto fs-2 fw-bolder">
      Create Post
    </div>
  </div>

  <div class="row justify-content-center">

    <div class="col-auto mb-4">
      <div class="card" style="width: 18rem; border-radius: 20px;">
        <div class="card-body">

          <form method="post" action="{% url 'webapp:post_create' %}" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="mb-3">
              <label class="form-label" for="cover_image">Cover Image:</label>
              <input class="form-control"  id="cover_image" type="file" name="cover_image" required>
            </div>

            <div class="mb-3">
              <label class="form-label" for="cover_title">Cover Title:</label>
              <input class="form-control" id="cover_title" type="text" name="cover_title" required>
            </div>

            <div class="mb-3">
              <label class="form-label" for="cover_description">Cover Description:</label>
              <input class="form-control" id="cover_description" type="text" name="cover_description" required>
            </div>

            <div class="row justify-content-center mt-4 mb-3">

              <div class="col-auto">
                <a href="{%  url 'webapp:index' %}" class="btn mx-1 btn-outline-secondary btn-sm rounded-4">Cancel</a>
              </div>

              <div class="col-auto">
                <input class="btn mx-1 btn-outline-primary btn-sm rounded-4" type="submit" value="Save">
              </div>

            </div>

          </form>

        </div>
      </div>
    </div>

  </div>

</div>

{% endblock %}

templates/webapp/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}


{% block content %}

  <div class="container">

    <div class="row mt-md-5 mt-1 justify-content-center">
      <div class="col-auto fs-2 fw-bolder">
        {{ post.cover_title }}
      </div>
    </div>

    <div class="row justify-content-center align-items-center">
      <div class="col-auto text-secondary text-center align-items-center">

        {% for tag in post.tags.all %}

          <div class="d-inline-flex align-items-center">
            {{ tag.tag_name }}

            <!-- Delete Button -->
            {%  if user.is_staff %}

              <form action="{% url 'webapp:tag_delete' post.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="tag_id" value="{{ tag.id }}">
                <button type="submit" class="btn btn-link p-0 m-0 px-1"><i class="bi bi-x-circle"></i></button>
              </form>

            {% endif %}
            {% if not forloop.last %} • {% endif %}
          </div>

        {% endfor %}

      </div>
    </div>

    <!-- Tag Form -->
    {%  if user.is_staff %}
      <div class="row justify-content-center align-items-center">
        <div class="col-auto">

          <form class="mt-3" method="POST" action="{% url 'webapp:tag_create' post.pk %}">
            {% csrf_token %}
            <div class="input-group">
              <input class="form-control form-control-sm rounded-start-5" aria-label="tag" name="tag_name" placeholder="" required>
              <button type="submit" class="btn btn-sm btn-outline-primary rounded-end-5"><i class="bi bi-tag"></i> Add Tag</button>
            </div>
          </form>

        </div>
      </div>
    {% endif %}

      <div class="row mt-md-3 mb-md-4 mt-2 mb-3 justify-content-center">
        <div id="post-field" class="col-11 col-md-8 col-lg-8 p-4 p-lg-5 border">

        {% for block in post.blocks.all %}
          <div class="row {%  if user.is_staff %}border-bottom{% endif %}">

          <!-- Position Change Buttons -->
          {%  if user.is_staff %}
            <div class="col-auto m-0 p-0 d-flex align-items-center">
              <form class="me-2" action="{% url 'webapp:block_change_position' post.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="block_id" value="{{ block.id }}">
                <input type="hidden" name="block_direction" value="up">
                <input type="hidden" name="direction" value="up">
                <button type="submit" {% if forloop.first %} disabled {% endif %} class="btn btn-link p-0 m-0"><i class="bi bi-arrow-up-circle"></i></button>
              </form>

              <form class="" action="{% url 'webapp:block_change_position' post.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="block_id" value="{{ block.id }}">
                <input type="hidden" name="block_direction" value="down">
                <input type="hidden" name="direction" value="down">
                <button type="submit" {% if forloop.last %} disabled {% endif %} class="btn btn-link p-0 m-0"><i class="bi bi-arrow-down-circle"></i></button>
              </form>
            </div>
          {% endif %}


          <div class="col">
            <!-- Render Text -->
            {% if block.content_object.text %}
                <div class="{{ block.content_object.text_alignment }}" id="{{ block.content_object.text_type }}">
                  {{ block.content_object.text|urlize }}
                </div>

            <!-- Render Image -->
            {% elif block.content_object.image %}
              <div class="{{ block.content_object.image_alignment }}">
                <img id="post-img-corners" class="img-fluid w-{{ block.content_object.image_size }}" src="{{ block.content_object.image.url }}" alt="img" />
              </div>

            <!-- Render Space -->
            {% elif block.content_object.space_number %}
              <div style="height: {{ block.content_object.space_number }}px;" class="text-center">
              {% if user.is_staff %}
                <span class="text-secondary fw-lighter text-center align-items-center">Space: {{ block.content_object.space_number }} px</span>
              {% endif %}
              </div>
            {% endif %}
          </div>


          <!-- Delete Button -->
          {%  if user.is_staff %}
            <div class="col-auto m-0 p-0 d-flex align-items-center">
              <form action="{% url 'webapp:block_delete' post.id %}" method="post" class="d-inline m-0 p-0">
                {% csrf_token %}
                <input type="hidden" name="block_id" value="{{ block.id }}">
                <button type="submit" class="btn btn-link p-0 m-0"><i class="bi bi-x-circle"></i></button>
              </form>
              <br>
            </div>
          {% endif %}

          </div>
        {% endfor %}

      </div>
    </div>

    <!-- Block Creation Panel -->
    {%  if user.is_staff %}
      {% include "includes/block_creation_panel.html" %}
    {% endif %}

    <!-- Render Comments -->
    <div class="row justify-content-center">
      <div class="col-auto mt-3 fs-4 fw-bolder text-center">
        {% if post.comments.all %}
          Comments
        {% else %}
          <span class="fs-5 fw-light text-secondary">There are no comments yet</span><br>
        {% endif %}
      </div>
    </div>

    {% for comment in post.comments.all %}
      <div class="row mt-2 mt-md-3 mb-3 mb-md-4 justify-content-center">
        <div id="post-field" class="col-11 col-md-8 col-lg-8 p-4 p-lg-5 border">

          <div class="row justify-content-between align-items-center">

            <div class="col-auto mb-2">
              <span class="fw-bold">
                <i class="bi bi-person-fill"></i>
                {{ comment.author.username }}&nbsp; &nbsp;
              </span>
              <span class="text-secondary fw-light">
                {{ comment.created_at|minus_hours:4|date:"d M Y" }} at
                {{ comment.created_at|minus_hours:4|date:"H:i" }}
              </span>
            </div>

            <!-- Delete Button -->
            {%  if user.is_staff or user == comment.author %}
            <div class="col-auto text-end">
                <div class="row justify-content-end m-0 p-0">
                  <div class="col-auto m-0 p-0">
                    <form action="{% url 'webapp:comment_delete' post.id %}" method="post" class="d-inline m-0 p-0">
                      {% csrf_token %}
                      <input type="hidden" name="comment_id" value="{{ comment.id }}">
                      <button type="submit" class="btn btn-link p-0 m-0"><i class="bi bi-x-circle"></i></button>
                    </form>
                  </div>
                </div>
            </div>
            {% endif %}
          </div>

          {{ comment.content }}

        </div>

      </div>
    {% endfor %}

    <!-- Comment Form -->
    {% if user.is_authenticated %}
      {% include "includes/comment_form.html" %}
    {% else %}
      <div class="row justify-content-center">
        <div  class="col-auto mt-0 mb-5">
          <a class="btn btn-outline-primary rounded-5 ms-2 mt-3 " href="{% url 'users:login' %}" role="button">Login to comment</a>
        </div>
      </div>
    {% endif %}

  </div>

{% endblock %}

templates/webapp/post_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}


{% block content %}


<div class="container">

  <div class="row mt-md-5 mb-md-4 mt-1 mb-3 justify-content-center">
    <div class="col-auto fs-2 fw-bolder">
      Edit Post
    </div>
  </div>

  <div class="row justify-content-center">

    <div class="col-auto mb-4">
      <div class="card" style="width: 18rem; border-radius: 20px;">
        <div class="card-body">

          <form method="post" action="{% url 'webapp:post_update' object.id %}" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="mb-3">
              <label class="form-label" for="cover_image">Cover Image:</label>
              <input class="form-control"  id="cover_image" type="file" name="cover_image" value="{{ form.cover_image.value }}">
            </div>

            <div class="mb-3">
              <label class="form-label" for="cover_title">Cover Title:</label>
              <input class="form-control" id="cover_title" type="text" name="cover_title" value="{{ form.cover_title.value }}">
            </div>

            <div class="mb-3">
              <label class="form-label" for="cover_description">Cover Description:</label>
              <input class="form-control" id="cover_description" type="text" name="cover_description" value="{{ form.cover_description.value }}">
            </div>

            <div class="row justify-content-center mt-4 mb-3">

              <div class="col-auto">
                <a href="{%  url 'webapp:index' %}" class="btn mx-1 btn-outline-secondary btn-sm rounded-4">Cancel</a>
              </div>

              <div class="col-auto">
                <input class="btn mx-1 btn-outline-primary btn-sm rounded-4" type="submit" value="Save">
              </div>

            </div>

          </form>

        </div>
      </div>
    </div>

  </div>

</div>

{% endblock %}